### PR TITLE
Fix Material-UI version to stable 0.20

### PR DESCRIPTION
**Pull request by anurag-majumdar**
I added the fix for material-ui version from 'next' to '0.20'. But there are some points regarding the application which are dependent on 'next', like 'CssBaseline' and 'Button'. These components need to be changed to the material-ui for 0.20 which is an older version and is different from material-ui@next beta.

I am continuing work in this area to streamline the components according to material-ui version 0.20.
Will be adding commits to this. 

Please let me know your thoughts on this.
@ritikrishu @realslimshanky @divyamrastogi @PrabhanshuAttri @palnabarun @nikitasharma2692

### CODE REVIEW

**Comment by anurag-majumdar** [comment]
While making changes to the version and looking at code changes, it looks like there are some new features which are going to be missed if we go back to 0.20. Also, the next version can be easily changed to the newest version once it comes out without much dependencies in future. Whereas, if we use 0.20 now, it will be a bit more challenging to refactor the whole application code I guess.

Let me know what you guys feel?
@realslimshanky @blenderskool @ritikrishu @divyamrastogi @palnabarun @nikitasharma2692

**Comment by blenderskool** [comment]
@realslimshanky @anurag-majumdar As of now, I don't see Material UI 0.20.0 being updated. If we continue using this stable version and when **next** version releases, we will have a hard time refactoring the code. Hence I feel we should continue using beta version as it can be easily updated for breaking changes in the future

**Comment by divyamrastogi** [comment]
@anurag-majumdar : Hey! You've got a few merge conflicts with master!
Usually, things don't break even with the `next` version, so it's fine to go ahead and keep using that and `next` version since it will always have the latest features.

**Comment by anurag-majumdar** [comment]
@divyamrastogi Let's close this request then. I think let's not merge this with the master and continue with the other front end work. 😃

**Pull request closed without merging**
