### PR TITLE
Add Design Guidelines (Design guidelines readme file #31)

### PR DESCRIPTION
**Pull request by anurag-majumdar**
1. A Design Guideline markdown file has been created.
2. Important points have been added.
3. Links to the style guide and the desktop screens have been added. The images have not been embedded to avoid cluttering of space.
4. A new section called Design Guidelines has been added to README.md file along with the link to the actual guideline.

Please review the changes. Thanks in advance.

### CODE REVIEW

**Comment by ritikrishu** [comment]
@anurag-majumdar thanks and congratulations on your first pull request ❤️

**Comment by ritikrishu** [comment]
Please try to create branches starting with issue number and give relative names to that it can be easy to match context in future!

**Comment by anurag-majumdar** [comment]
@divyamrastogi  @ritikrishu Thanks! Sure, will keep that in mind for next one. 😃

**Comment by anurag-majumdar** [comment]
A gentle reminder, I guess the merge has not been completed yet. Requesting remaining moderators to review the same. Thanks. 😃

**Comment by realslimshanky** [comment]
Thank you for your contribution @anurag-majumdar :taco:

**Pull request merged**
